### ISSUE TITLE
Implement unregister agent

### ISSUE THREAD

**Issue by Sonkun** [yorokobicom/agent#9]
How do you want that ? 

```
yorokobi unregister 
```
or 
```
yorokobi-unregister
```
or else ?

**Comment by pelcasandra** [comment]
It seems to me that ```yorokobi unregister``` feels cleaner as we can also use this schema for future commands.

**Comment by Sonkun** [comment]
OKi ! I'll do that tonight.

**Comment by Sonkun** [comment]
what is the HTTP request to unregister an agent ? my Postman account stopped working

**Comment by pelcasandra** [comment]
You just send a `DELETE` request instead of `POST` one to the agent route including the agent token like this. 

    http://api.yorokobi.co/v1/agents/fYydLUcRwAXP2geMnVDM

That should be it. I remember I sent you a JSON file with all the requests to import in Postman. You may not need a Postman user at all to import those (not sure), but in any case you can create a new one. Its free and handy :)

**Comment by Sonkun** [comment]
That's helpful, thank you :)

I got this reply from server: 

```
422
{'errors': {'base': ['You can not register this agent. You reached your limit of 3 agents. You need to upgrade to a higher plan.']}}
```

Using this: `https://api.yorokobi.com/v1/agents/CCMgmS99JTV7s98kc` with my account (you know my license key I supposed).

Any clue ? ?

**Comment by pelcasandra** [comment]
Oops.. I just pushed a fix for that. Please try again.

**Comment by Sonkun** [comment]
Implemented ! :)
